### PR TITLE
Metallb image is depreciated

### PR DESCRIPTION
**Pull request by InaKeitaro**
This PR is related to: https://github.com/keitaroinc/devops-enabler/issues/26

Newer versions of Metallb are configured using a CDR (Custom Resource Definition) .yaml file, which should be applied to the metallb settings.

### CODE REVIEW

**Comment by gocemitevski** [comment]
@InaKeitaro @nadica-rizova we should not have hard-coded IP addresses or versions in the code. Ideally, this should all be configurable.

**Comment by InaKeitaro** [comment]
@gocemitevski The IP addresses are not hard-coded, they are taken from the kind network subnet. The version is hard-coded. I can make the version be as an argument in the command with some default value, so that it is always defined.

**Comment by gocemitevski** [comment]
@InaKeitaro what about these:

- https://github.com/keitaroinc/devops-enabler/pull/45/files#diff-f7529186bc9dfc85df009e886e9fae90ed008d242b934aeb33be5134eca52054R8
- https://github.com/keitaroinc/devops-enabler/pull/45/files#diff-df29459bc8cf3ac5cf7c35a268a477fb5b64a35c08d6cd2c01cad5157882a612R205

**Comment by InaKeitaro** [comment]
@gocemitevski The version of metallb is hard-coded, but the IP addresses aren't. In cmd-setup.py line 158-170 with  yaml.dump_all(config, yaml_file, default_flow_style=False) the IP addresses are reassigned. The ones in the .yaml are there from before as a default value, but if they are different for another machine they will be set to the current value.

**Review by nadica-rizova — APPROVED** [review]
the new version of metallb is tested and works ok

**Pull request merged**
