### PR TITLE
Modify version() and release() functions

### PR DESCRIPTION
**Pull request by teodora-aleksovska**
This pull request contains resolved issues with version() and release() functions for the enabler platform command.

### CODE REVIEW

**Comment by gocemitevski** [comment]
@teodora-aleksovska can you also provide case scenarios for both the `version` and `release` commands - basically, testing instructions.

**Comment by teodora-aleksovska** [comment]
@gocemitevski Certainly, I tested these commands on VMT, and after executing _enabler platform version_ and _enabler platform release <version> <submodule_name>_ , I received these outputs:

teodora@teodora-ThinkPad-T16-Gen-1:~/vmt-platform/enabler$ enabler platform version
REPO
<git.repo.base.Repo '/home/teodora/vmt-platform/.git'>
platform/vmt-common: test
platform/microservice-deal: v1.4.2
platform/microservice-floor-rate: Error retrieving version
platform/vmt-ui-components: v1.4.2
infrastructure/seed-data: Error retrieving version
platform/microservice-product: Error retrieving version
platform/microservice-preffered-route: v1.4.2
platform/microservice-origin: Error retrieving version
platform/microservice-customer: Error retrieving version
platform/microservice-reference-data: v1.4.2
platform/microservice-route: Error retrieving version
platform/microservice-country: v1.4.2
platform/vmt-ui-core: v1.4.2
platform/vmt-ui-deals: v1.4.2
platform/vmt-ui-theme: v1.4.2
platform/vmt-ui-platform: v1.4.2
platform/vmt-ui-nav: v1.4.2
platform/vmt-ui-floor: Error retrieving version
platform/vmt-ui-customers: Error retrieving version
platform/microservice-users: v1.4.2
platform/microservice-calculation: v1.4.2
platform/microservice-customer-rate-mod: Error retrieving version
platform/microservice-customer-rate: Error retrieving version
platform/microservice-netezza: v1.4.2
platform/microservice-deal-lock: v1.4.2
platform/vmt-ui-users: Error retrieving version
platform/vmt-ui-obr-buckets: v2.1.7
platform/microservice-obr: microservice-obr-v2.1.7
database/cmrs: Error retrieving version
platform/vmt-techwiki: VMT-TechWiki-v1.0.1
platform/microservice-iflow: Error retrieving version
platform/vmt-ui-numbering-plan: vmt_np_country_1.0.0
platform/microservice-np-countries: vmt_np_country_1.0.0
platform/microservice-customer-automation: Error retrieving version
platform/microservice-customer-attributes: Error retrieving version
platform/microservice-np-network-mapping: Error retrieving version
platform/vmt-ui-dynamic-routing: group_routing_p1_save_all_OBR_types
platform/microservice-group-routing: group_routing_p1_save_all_OBR_types
platform/microservice-mapping-prefixes: Error retrieving version
platform/microservice-blocking: Error retrieving version
platform/microservice-sales: Error retrieving version
platform/microservice-floor-rate-v1: Error retrieving version
platform/vmt-ui-mapping: Error retrieving version
platform/vmt-ui-blocking: Error retrieving version
platform/vmt-ui-snr: Error retrieving version
platform/microservice-snr: Error retrieving version
platform/vmt-ui-features: Error retrieving version
platform/microservice-features: Error retrieving version


teodora@teodora-ThinkPad-T16-Gen-1:~/vmt-platform/enabler$ enabler platform release 2.1.7 /home/teodora/vmt-platform/platform/microservice-obr
Platform version: v2.1.7
microservice-obr version: v2.1.7

**Comment by gocemitevski** [comment]
@teodora-aleksovska can you please document what is the expected output for both commands? Doesn't matter which project enabler is being used on. What is the expected output of the commands in general, not specifically on your machine.

**Comment by teodora-aleksovska** [comment]
release: The release command releases the platform by tagging the platform repository and tagging all individual components (submodules) using their respective SHA that the submodules point to.

version: The version command checks the versions of microservices in submodules.

**Comment by gocemitevski** [comment]
@teodora-aleksovska OK. Please add all relevant descriptions in the README as well for each command. https://github.com/keitaroinc/enabler?tab=readme-ov-file#commands. The changes in the README should also be included in this branch.

**Pull request merged**
