### PR TITLE
Setup init improvements

### PR DESCRIPTION
**Pull request by teodora-aleksovska**
This PR includes improvements to enabler setup init command. It now checks whether binaries already exist before downloading them.

After running enabler setup init, i received this output:

teodora@teodora-ThinkPad-T16-Gen-1:~/Project/enabler$ enabler setup init 
Bin folder already exists. Continue...
-kubectl already exists at: bin/kubectl
helm already exists at: bin/helm
istioctl already exists at: bin/istioctl
kind already exists at: bin/kind
skaffold already exists at: bin/skaffold

### CODE REVIEW

**Comment by gocemitevski** [comment]
@teodora-aleksovska please describe what happens is some of the binaries does not exist - the mixed case scenario.

**Comment by teodora-aleksovska** [comment]
@gocemitevski after running the enabler setup init command, it will check if the binaries exist in the bin folder. If some of them do not exist, this command will download them.

Before these improvements, the downloading process worked correctly every time after running enabler setup init.

**Comment by gocemitevski** [comment]
@teodora-aleksovska OK. Please add all relevant descriptions in the README as well for each command. https://github.com/keitaroinc/enabler?tab=readme-ov-file#commands.

**Comment by gocemitevski** [comment]
The changes in the README should also be included in the `feature-setup-init-improvements` branch.

**Comment by teodora-aleksovska** [comment]
@gocemitevski additionally, this pull request includes the required changes in the README file and unit tests.

**Review by gocemitevski — APPROVED** [review]

**Pull request merged**
